apiVersion: appstudio.redhat.com/v1alpha1
kind: IntegrationTestScenario
metadata:
  name: example-test-app
spec:
  application: application-sample
  bundle: 'quay.io/redhat-appstudio/example-tekton-bundle:integration-test-app'
  pipeline: integration-test-app
  environment:
    name: development
    type: POC
    configuration:
      env: []

