apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  name: example-fail
  namespace: default
spec:
  application: application-sample
  contexts:
    - description: Application testing
      name: application
  resolverRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/konflux-ci/integration-examples
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/integration_pipeline_fail.yaml
