apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: snapshot-sample
  namespace: default
  labels:
    test.appstudio.openshift.io/type: override
spec:
  application: application-sample
  components:
    - containerImage: quay.io/redhat-user-workloads/default/application-sample/component-sample@sha256:0db0a473a6abf5c15c424ab07cfbd5c40c06622fe648d4fe6a6b6abc224a0d0c
      name: component-sample
      source:
        git:
          url: https://github.com/sample-org/sample-repo
          revision: fa8b89274a61ef0f1c257b7a84c37aa2ec844109
