---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: build-pipelinerun-
  annotations:
    "appstudio.redhat.com/updateComponentOnSuccess": "false"
    chains.tekton.dev/signed: "true"
  labels:
    pipelines.appstudio.openshift.io/type: "build"
    pipelines.openshift.io/used-by: "build-cloud"
    pipelines.openshift.io/runtime: "nodejs"
    pipelines.openshift.io/strategy: "s2i"
    appstudio.openshift.io/component: "component-sample"
spec:
  pipelineRef:
    resolver: bundles
    params:
      - name: bundle
        value: quay.io/redhat-appstudio/example-tekton-bundle:build-pipeline-pass
      - name: name
        value: build-pipeline-pass
      - name: kind
        value: pipeline
  params:
    - name: output-image
      value: "quay.io/redhat-appstudio/sample-image"
    - name: image-digest
      value: "sha256:98f7c02fc24f9a66a39660ecae95bf0e84660e62281d98d660cb4517ad69c17b"
    - name: git-url
      value: "https://github.com/konflux-ci/integration-examples"
    - name: revision
      value: "65cee801fcffa9c1de0be101cfbdd4577ed0da53"