---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: integration-pipelinerun-
  labels:
    pipelines.appstudio.openshift.io/type: "test"
    test.appstudio.openshift.io/test: "component"
    appstudio.openshift.io/snapshot: "snapshot-sample"
    appstudio.openshift.io/component: "component-sample"
    appstudio.openshift.io/application: "application-sample"
    test.appstudio.openshift.io/scenario: "integrationtestscenario-sample1"
spec:
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: http://github.com/konflux-ci/integration-examples.git
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/integration_test_app.yaml
  workspaces:
    - name: cluster-credentials
      secret:
        secretName: cluster-credentials-secret