---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: integration-pipelinerun-
  annotations:
    pipelinesascode.tekton.dev/on-target-branch: '[main]'
    pipelinesascode.tekton.dev/repo-url:
    pipelinesascode.tekton.dev/sha-title: 'Merge pull request #35 from psturc/PLNSRVCE-281-vol2'
    pipelinesascode.tekton.dev/git-auth-secret: pac-gitauth-nthx
    pipelinesascode.tekton.dev/max-keep-runs: '5'
    pipelinesascode.tekton.dev/sha-url:
    pipelinesascode.tekton.dev/on-event: '[push]'
    pipelinesascode.tekton.dev/installation-id: '43840620'
  labels:
    pipelines.appstudio.openshift.io/type: "test"
    test.appstudio.openshift.io/test: "component"
    appstudio.openshift.io/snapshot: "snapshot-sample"
    appstudio.openshift.io/component: "component-sample"
    appstudio.openshift.io/application: "application-sample"
    test.appstudio.openshift.io/scenario: "integrationtestscenario-sample1"
    pipelinesascode.tekton.dev/event-type: push
    pipelinesascode.tekton.dev/state: completed
    pipelinesascode.tekton.dev/sender: psturc
    pipelinesascode.tekton.dev/check-run-id: '7108761088'
    pipelinesascode.tekton.dev/branch: refs-heads-main
    pipelinesascode.tekton.dev/url-org: redhat-appstudio
    pipelinesascode.tekton.dev/original-prname: build-service-on-push
    pipelinesascode.tekton.dev/url-repository:
    pipelinesascode.tekton.dev/repository:
    pipelinesascode.tekton.dev/sha:
    pipelinesascode.tekton.dev/git-provider: github
spec:
  pipelineRef:
    resolver: bundles
    params:
      - name: bundle
        value: quay.io/redhat-appstudio/example-tekton-bundle:integration-pipeline-fail
      - name: name
        value: integration-pipeline-fail
      - name: kind
        value: pipeline