apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: integration-environment-pipeline-pass
spec:
  tasks:
    - name: task-success
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/integration-examples 
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/test_output.yaml
      params:
        - name: RESULT
          value: SUCCESS
    - name: provision-env-with-ephemeral-namespace
      taskRef:
        resolver: bundles
        params:
          - name: bundle
            value: quay.io/redhat-appstudio-tekton-catalog/task-eaas-provision-space:0.1@sha256:47cc4f5adfc2d0d5c6670a9c13f350e2dcd41bae3275497910e2fec900168c60
          - name: name
            value: eaas-provision-space
          - name: kind
            value: task
      params:
        - name: ownerName
          value: $(context.pipelineRun.name)
        - name: ownerUid
          value: $(context.pipelineRun.uid)
    - name: task-success-2
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/integration-examples 
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/test_output.yaml
      params:
        - name: RESULT
          value: SKIPPED

