apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: test-app
spec:
  description: >-
    Expects an Snapshot deployed.
  params:
    - name: SNAPSHOT
      description: The json string of the Snapshot under test 
  steps:
    - image: quay.io/redhat-appstudio/konflux-test:latest
      env:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
      script: |
        echo -e "${SNAPSHOT}"
